### ISSUE TITLE
Exception when PCAN driver is not available

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/cvra-bootloader#1]
Commit bc674f5 brought support for Peak-System's PCAN-USB adapter.
However, if the Windows standalone executable, generated by PyInstaller using the script from commit  68b8802, is called on a PC, which doesn't have the driver installed, an exception can occur:

````sh$ ./bootloader_read_config.exe -i pcan
[11468] Failed to execute script read_config
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 172, in __init__
  File "ctypes\__init__.py", line 351, in __init__
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cvra_bootloader\read_config.py", line 83, in <module>
  File "cvra_bootloader\read_config.py", line 37, in main
  File "cvra_bootloader\utils.py", line 70, in open_connection
  File "can\adapters\peak_pcan.py", line 13, in __init__
  File "can\adapters\PCAN_Basic\Include\PCANBasic.py", line 342, in __init__
  File "ctypes\__init__.py", line 429, in LoadLibrary
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 174, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'PCANBasic'. Most probably this dynlib/dll was not found when the application was frozen.
````

**Comment by matthiasbock** [comment]
Fixed with commits fa875bc28f21eb087f09b4ad1b333b03c52fb761 and 112303a31eb4f7a802e00752f48a090149959639.
