### ISSUE TITLE
AttributeError: module 'socket' has no attribute 'AF_CAN'

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/cvra-bootloader#3]
Packaged the Python client from commit 112303a31eb4f7a802e00752f48a090149959639 using PyInstaller 3.3 on Windows 7 64-Bit and ran it:

````sh
./bootloader_invoke.exe -i can0 1
[6732] Failed to execute script invoke
Traceback (most recent call last):
  File "cvra_bootloader\invoke.py", line 130, in <module>
  File "cvra_bootloader\invoke.py", line 90, in main
  File "cvra_bootloader\utils.py", line 87, in open_connection
  File "can\adapters\socketcan.py", line 25, in __init__
AttributeError: module 'socket' has no attribute 'AF_CAN'
````

**Comment by matthiasbock** [comment]
Tested with Windows 8 64-Bit. Works: The above exception is replaced by a nice error message.
