### ISSUE TITLE
msgpack.exceptions.ExtraData: unpack(b) received extra data.

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/cvra-bootloader#9]
System: Linux 64-Bit
Commit: Bootloader and client from revision c96148e9ee405c696d43f2e23e4e3ca3e30c6259 with uncommitted changes
Setup: CANtact with firmware revision matthiasbock/cantact-fw@a0e1d798c11be2f2c653a38c823aa2101b71caca possibly with minor uncommitted changes, attached to can0 by slcand, operating at 1 Mbps

````sh
$ bootloader_flash -i can0 1 -c "Test" -f test.elf -vv
INFO:root:File format: ELF image
INFO:root:Invoking arm-none-eabi-objdump to list ELF sections...
INFO:root:Parsing section table...
INFO:root:Found section: .isr_vector
INFO:root:Extracted target address: 0x08010000
INFO:root:Converting ELF to binary: test.elf -> test.bin
INFO:root:Flashing to address: 0x08010000
INFO:root:Selected SocketCAN interface.
INFO:root:Searching for bootloader nodes...
DEBUG:root:Transmitting command...
DEBUG:root:Transmitting CAN frame via socket...
DEBUG:root:Transmitting CAN frame via socket...
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Datagram successfully decoded.
0a 8d 02 0b 82 1b cf 54 82 d3 90 f5 f7 a2 5c 44 d5 d0 bb f2 60 42 41 84 d3 c0 61 89 c0 fd d4 b3 52 b9 d9 5d 26 96 db 17 dd 70 6e 6b 09 38 c1 a0 fa cc 1f cb 4c 30 d0 56 aa c3 86 ce a4 84 95 c2 e4 8b c4 1d af c5 4f e0 e6 f4 3d 20 2f 5a 34 6d f6 3f 67 e9 88 b3 07 26 73 03 76 29 00 85 00 34 40 46 aa 3b f8 c2 a1 7f 3e b3 35 bf 66 c9 19 9c f5 77 2d 2a 54 98 af 82 a3 ea 2f af 30 01 7c 33 b8 86 10 53 8c 6d cb 6b 68 f1 c1 a6 46 78 92 65 fe de e3 15 a7 77 2c 98 33 ad 5b 7e ed d0 c9 93 da e1 73 73 d0 e0 62 4c 7c ed e9 74 f6 ee 86 fd d5 85 de 67 ce c5 05 c2 e5 e3 36 2d cc cf dc 6e 3d f8 b0 6b 45 c9 08 07 57 7a 57 27 e3 e2 36 6e da ed ba ab 89 9b 44 3f a9 fb 54 32 ce d2 63 9e 92 15 2c 32 0b 35 92 9e 6d 3d f5 37 a9 4f 13 43 9e 65 b3 06 2b 1e 38 4c 33 45 a9 
INFO:root:Node 1 is online.
Flashing firmware, size: 76556 bytes
Erasing pages...
N/A% (0 of 76556) |                                                                                                                                                                      | Elapsed Time: 0:00:00 ETA:  --:--:--INFO:root:Initiating transmission (attempt 1/6)...
DEBUG:root:Transmitting command...
DEBUG:root:Transmitting CAN frame via socket...
DEBUG:root:Transmitting CAN frame via socket...
DEBUG:root:Transmitting CAN frame via socket...
DEBUG:root:Transmitting CAN frame via socket...
DEBUG:root:Transmitting CAN frame via socket...
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Received CAN frame from socket.
DEBUG:root:Datagram successfully decoded.
0a 8d 02 0b 82 1b cf 54 82 d3 90 f5 f7 a2 5c 44 d5 d0 bb f2 60 42 41 84 d3 c0 61 89 c0 fd d4 b3 52 b9 d9 5d 26 96 db 17 dd 70 6e 6b 09 38 c1 a0 fa cc 1f cb 4c 30 d0 56 aa c3 86 ce a4 84 95 c2 e4 8b c4 1d af c5 4f e0 e6 f4 3d 20 2f 5a 34 6d f6 3f 67 e9 88 b3 07 26 73 03 76 29 00 85 00 34 40 46 aa 3b f8 c2 a1 7f 3e b3 35 bf 66 c9 19 9c f5 77 2d 2a 54 98 af 82 a3 ea 2f af 30 01 7c 33 b8 86 10 53 8c 6d cb 6b 68 f1 c1 a6 46 78 92 65 fe de e3 15 a7 77 2c 98 33 ad 5b 7e ed d0 c9 93 da e1 73 73 d0 e0 62 4c 7c ed e9 74 f6 ee 86 fd d5 85 de 67 ce c5 05 c2 e5 e3 36 2d cc cf dc 6e 3d f8 b0 6b 45 c9 08 07 57 7a 57 27 e3 e2 36 6e da ed ba ab 89 9b 44 3f a9 fb 54 32 ce d2 63 9e 92 15 2c 32 0b 35 92 9e 6d 3d f5 37 a9 4f 13 43 9e 65 b3 06 2b 1e 38 4c 33 45 a9 
DEBUG:root:Transmission succeeded.
Traceback (most recent call last):
  File "cvra-bootloader/client/env/bin/bootloader_flash", line 11, in <module>
    load_entry_point('cvra-bootloader==2.1.0', 'console_scripts', 'bootloader_flash')()
  File "cvra-bootloader/client/env/lib/python3.5/site-packages/cvra_bootloader-2.1.0-py3.5.egg/cvra_bootloader/bootloader_flash.py", line 464, in main
  File "cvra-bootloader/client/env/lib/python3.5/site-packages/cvra_bootloader-2.1.0-py3.5.egg/cvra_bootloader/bootloader_flash.py", line 110, in flash_image
  File "cvra-bootloader/client/env/lib/python3.5/site-packages/cvra_bootloader-2.1.0-py3.5.egg/cvra_bootloader/bootloader_flash.py", line 111, in <listcomp>
  File "msgpack/_unpacker.pyx", line 143, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2143)
msgpack.exceptions.ExtraData: unpack(b) received extra data.
````

**Comment by matthiasbock** [comment]
Apparently this problem was caused by a mismatch in command set version (3 in the bootloader, 2 in the client). Such a mismatch should be handled gracefully.
